#!/bin/sh /etc/rc.common
# Copyright (C) 2023 Tianling Shen <cnsztl@immortalwrt.org>

USE_PROCD=1
START=99

extra_command "hot_reload" "Hot-reload service"

CONF="dae"
PROG="/usr/bin/dae"
LOG_DIR="/var/log/dae"

start_service() {

	"$PROG" validate -c "/etc/dae/config.dae" || return 1



	procd_open_instance "$CONF"
	procd_set_param command "$PROG" run
	procd_append_param command --config "/etc/dae/config.dae"
	procd_append_param command --disable-timestamp
	procd_append_param command --logfile "$LOG_DIR/dae.log"
	procd_append_param command --logfile-maxbackups "1"
	procd_append_param command --logfile-maxsize "1"

	procd_set_param limits core="unlimited"
	procd_set_param limits nofile="1000000 1000000"
	procd_set_param respawn
	# procd_set_param stdout 1
	procd_set_param stderr 1

	procd_close_instance
}

stop_service() {
	rm -rf "$LOG_DIR"
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}

hot_reload() {
	"$PROG" reload "$(cat /var/run/dae.pid)"
}
