#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1

PROG="/usr/bin/dae"
CONF="/etc/dae/run.dae"

start_service() {
        procd_open_instance dae
        procd_set_param respawn ${respawn_threshold:-0} ${respawn_timeout:-10} ${respawn_retry:-0}
        procd_set_param stdout 1 # forward stdout of the command to logd
        procd_set_param stderr 1 # same for stderr
        # procd_set_param user nobody
        procd_set_param command "$PROG"

        procd_append_param command run --disable-timestamp -c "$CONF"

        procd_close_instance
}