#!/bin/sh /etc/rc.common
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=99

USE_PROCD=1

PROG=/usr/bin/sing-box
HOME=/etc/local/sing-box

start_service() {
	procd_open_instance sing-box
	procd_set_param respawn ${respawn_threshold:-0} ${respawn_timeout:-10} ${respawn_retry:-0}
	procd_set_param stdout 1 # forward stdout of the command to logd
	procd_set_param stderr 1 # same for stderr
	# procd_set_param user nobody
	procd_set_param command "$PROG"

	procd_append_param command run -D "$HOME"

	procd_close_instance
}