mixed-port: 7890
log-level: info
mode: Rule
external-controller: 0.0.0.0:9090
ipv6: true

dns:
  enable: true
  listen: '127.0.0.1:8853'
  use-hosts: true
  default-nameserver: [192.168.1.1, 223.5.5.5, 223.6.6.6, 180.184.1.1, 180.184.2.2, 119.29.29.29]
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-filter: []
  nameserver: ['192.168.1.1', 'https://1.12.12.12/dns-query', 'https://120.53.53.53/dns-query', 'https://223.5.5.5/dns-query']
  nameserver-policy: {}
  fallback: []
  fallback-filter: {}

hosts:

profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    TLS:
    HTTP:
  sniffing:
    - tls
    - http

experimental:
  sniff-tls-sni: true


proxy-providers:
  example:
    type: http
    url: "https://example.com"
    path: ./proxy_provider/example.yaml
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - AUTO
      - load-balance
      - DIRECT
    use:
      - example

  - name: "AUTO"
    type: url-test
    use:
      - example
    url: 'http://cp.cloudflare.com'
    interval: 300

  - name: "load-balance"
    type: load-balance
    use:
      - example
    url: 'http://cp.cloudflare.com'
    interval: 300
    lazy: true
    disable-udp: false
    strategy: round-robin

  - name: "HK"
    type: url-test
    filter: "香港"
    use:
      - example
    url: 'http://cp.cloudflare.com'
    interval: 300

  - name: "TW"
    type: url-test
    filter: "台湾"
    use:
      - example
    url: 'http://cp.cloudflare.com'
    interval: 300

  - name: "JP"
    type: url-test
    filter: "日本"
    use:
      - example
    url: 'http://cp.cloudflare.com'
    interval: 300

  - name: "US"
    type: url-test
    filter: "美国"
    use:
      - example
    url: 'http://cp.cloudflare.com'
    interval: 300

  - name: "SG"
    type: url-test
    filter: "新加坡"
    use:
      - example
    url: 'http://cp.cloudflare.com'
    interval: 300

  - name: "BYPASS"
    type: select
    proxies:
      - DIRECT
      - PROXY

  - name: "Other"
    type: select
    proxies:
      - PROXY
      - DIRECT


rule-providers:
# https://github.com/blackmatrix7/ios_rule_script
  paypal:
    type: http
    behavior: classical
    url : "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.yaml"
    path: ./rule_provider/paypal.yaml
    interval: 86400
  niconico:
    type: http
    behavior: classical
    url : "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Niconico/Niconico.yaml"
    path: ./rule_provider/niconico.yaml
    interval: 86400
  dmm:
    type: http
    behavior: classical
    url : "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DMM/DMM.yaml"
    path: ./rule_provider/dmm.yaml
    interval: 86400
  bahamut:
    type: http
    behavior: classical
    url : "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bahamut/Bahamut.yaml"
    path: ./rule_provider/bahamut.yaml
    interval: 86400
  ehentai:
    type: http
    behavior: classical
    url : "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EHGallery/EHGallery.yaml"
    path: ./rule_provider/ehentai.yaml
    interval: 86400
  pixiv:
    type: http
    behavior: classical
    url : "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Pixiv/Pixiv.yaml"
    path: ./rule_provider/pixiv.yaml
    interval: 86400
  twitch:
    type: http
    behavior: classical
    url : "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitch/Twitch.yaml"
    path: ./rule_provider/twitch.yaml
    interval: 86400
  youtube:
    type: http
    behavior: classical
    url : "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"
    path: ./rule_provider/youtube.yaml
    interval: 86400
  twitter:
    type: http
    behavior: classical
    url : "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml"
    path: ./rule_provider/twitter.yaml
    interval: 86400
  facebook:
    type: http
    behavior: classical
    url : "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook.yaml"
    path: ./rule_provider/facebook.yaml
    interval: 86400
  instagram:
    type: http
    behavior: classical
    url : "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.yaml"
    path: ./rule_provider/instagram.yaml
    interval: 86400

# https://github.com/Loyalsoldier/clash-rules/
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

# https://www.dogfight360.com/blog/knowledge-base/fix_steamdl_region/
  steamip:
    type: http
    behavior: ipcidr
    url: "https://gist.githubusercontent.com/Nelocompne/362713bad791f0904be9217cca52a3df/raw/6997b9fe43c8a9fe216f209563836a70742fe01e/steamip.yaml"
    path: ./game_rules/steamip.yaml
    interval: 86400

  steamdomain:
    type: http
    behavior: domain
    url: "https://gist.githubusercontent.com/Nelocompne/362713bad791f0904be9217cca52a3df/raw/6997b9fe43c8a9fe216f209563836a70742fe01e/steamdomain.yaml"
    path: ./game_rules/steamdomain.yaml
    interval: 86400


rules:
#  - RULE-SET,applications,BYPASS
  - DOMAIN,cp.cloudflare.com,Other
  - DOMAIN,clash.razord.top,BYPASS
  - DOMAIN,yacd.haishan.me,BYPASS
  - DOMAIN,clash.metacubex.one,BYPASS
  - DOMAIN,yacd.metacubex.one,BYPASS
  - DOMAIN,d.metacubex.one,BYPASS
# steam ↓
  - RULE-SET,steamdomain,BYPASS
  - RULE-SET,steamip,BYPASS
# steam ↑
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
# custom
  - RULE-SET,paypal,BYPASS
  - RULE-SET,ehentai,load-balance
  - RULE-SET,bahamut,TW
  - RULE-SET,patreon,US
  - RULE-SET,twitch,US
  - RULE-SET,dmm,JP
  - RULE-SET,niconico,JP
  - RULE-SET,pixiv,JP
  - RULE-SET,twitter,JP
  - RULE-SET,youtube,TW
  - RULE-SET,instagram,HK
  - RULE-SET,facebook,HK
  - RULE-SET,telegramcidr,SG
# custom
  - RULE-SET,icloud,BYPASS
  - RULE-SET,apple,BYPASS
  - RULE-SET,google,BYPASS
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,BYPASS
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,BYPASS
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,BYPASS
  - MATCH,Other
